version: "3.9"
services:
  db:
    image: mysql:8.0.30
    platform: linux/x86_64
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypass1
      MYSQL_DATABASE: springbook
      MYSQL_USER: spring
      MYSQL_PASSWORD: book
      TZ: Asia/Seoul
    volumes:
      - ../db/mysql/data:/var/lib/mysql
      - ../db/mysql/config:/etc/mysql/conf.d
      - ../db/mysql/init:/docker-entrypoint-initdb.d
